version: '3'
services:
  db:
    image: postgis/postgis
    restart: always
    env_file:
      - .env
    container_name: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data
  nestjs:
    image: ghcr.io/artcann/friendly_meme:latest
    env_file:
      - .env
    ports:
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: backend-friendly-meme-nest
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pgdata:
  pgadmin-data: