version: '3'
services: 
  db:
    image: postgis/postgis
    restart: always
    environment: 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nestjs:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: ghcr.io/artcann/friendly_meme:latest
    environment: 
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - APP_PORT=${PORT}
      - REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      
    ports: 
      - "3000:3000" # expose-to-the-world : only-in-the-docker
    container_name: backend-friendly-meme-nest
    depends_on: 
      - db
    volumes: 
      - .:/app
      - /app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports: 
      - "8080:80"
    volumes: 
      - ./pgadmin:/var/lib/pgadmin
    depends_on: 
      - db
volumes:
  pgdata:
  pgadmin-data: